---
# tasks file for aws-cli-tools
- name: Install AWS CLI Tools
  pip: >
    name=awscli
  become: yes
  tags: 'aws_cli_tools.install'

- name: Create config dir
  file: 'path={{aws_users_home_dir}}//.aws mode=0755 state=directory'
  with_items: '{{aws_cli_users}}'
  tags: 'aws_cli_tools.config'
